INSERT INTO genero (generoId, nombre) VALUES (28,'Acci&oacute;n');
INSERT INTO genero (generoId, nombre) VALUES (12,'Aventura');
INSERT INTO genero (generoId, nombre) VALUES (16,'Animaci&oacute;n');
INSERT INTO genero (generoId, nombre) VALUES (35,'Comedia');
INSERT INTO genero (generoId, nombre) VALUES (80,'Crimen');
INSERT INTO genero (generoId, nombre) VALUES (99,'Documental');
INSERT INTO genero (generoId, nombre) VALUES (18,'Drama');
INSERT INTO genero (generoId, nombre) VALUES (10751,'Familia');
INSERT INTO genero (generoId, nombre) VALUES (14,'Fantas&iacute;a');
INSERT INTO genero (generoId, nombre) VALUES (10769,'Foreign');
INSERT INTO genero (generoId, nombre) VALUES (36,'Historia');
INSERT INTO genero (generoId, nombre) VALUES (27,'Terror');
INSERT INTO genero (generoId, nombre) VALUES (10402,'M&uacute;sica');
INSERT INTO genero (generoId, nombre) VALUES (9648,'Misterio');
INSERT INTO genero (generoId, nombre) VALUES (10749,'Romance');
INSERT INTO genero (generoId, nombre) VALUES (878,'Ciencia ficci&oacute;n');
INSERT INTO genero (generoId, nombre) VALUES (10770,'pel&iacute;cula de la televisi&oacute;n');
INSERT INTO genero (generoId, nombre) VALUES (53,'Suspense');
INSERT INTO genero (generoId, nombre) VALUES (10752,'Guerra');
INSERT INTO genero (generoId, nombre) VALUES (37,'Western');


INSERT INTO pelicula (peliculaId, nombre, anio, generoId) VALUES (76341,'Mad Max: Furia en la carretera',2015, 28);
INSERT INTO pelicula (peliculaId, nombre, anio, generoId) VALUES (207703,'Kingsman: Servicio Secreto',2014, 28);
INSERT INTO pelicula (peliculaId, nombre, anio, generoId) VALUES (99861,'Vengadores: La era de Ultr&oacute;n',2015, 28);
INSERT INTO pelicula (peliculaId, nombre, anio, generoId) VALUES (76757,'El destino de J&uacute;piter',2015, 28);
INSERT INTO pelicula (peliculaId, nombre, anio, generoId) VALUES (177572,'Big Hero 6',2014, 28);
INSERT INTO pelicula (peliculaId, nombre, anio, generoId) VALUES (245891,'John Wick',2014, 28);
INSERT INTO pelicula (peliculaId, nombre, anio, generoId) VALUES (168259,'Fast & Furious 7',2015, 28);
INSERT INTO pelicula (peliculaId, nombre, anio, generoId) VALUES (260346,'V3nganza',2014, 28);
INSERT INTO pelicula (peliculaId, nombre, anio, generoId) VALUES (9659,'Mad Max, salvajes de autopista',1979, 28);
INSERT INTO pelicula (peliculaId, nombre, anio, generoId) VALUES (198184,'Chappie',2015, 28);
INSERT INTO pelicula (peliculaId, nombre, anio, generoId) VALUES (147441,'Exodus: Dioses y reyes',2014, 28);
INSERT INTO pelicula (peliculaId, nombre, anio, generoId) VALUES (228150,'Corazones de acero',2014, 28);
INSERT INTO pelicula (peliculaId, nombre, anio, generoId) VALUES (337339,'Fast & Furious 8',2017, 28);
INSERT INTO pelicula (peliculaId, nombre, anio, generoId) VALUES (158852,'Tomorrowland',2015, 28);
INSERT INTO pelicula (peliculaId, nombre, anio, generoId) VALUES (135397,'Jurassic World: Parque jur&aacute;sico IV',2015, 28);
INSERT INTO pelicula (peliculaId, nombre, anio, generoId) VALUES (190859,'El francotirador',2014, 28);
INSERT INTO pelicula (peliculaId, nombre, anio, generoId) VALUES (9355,'Mad Max III, m&aacute;s all&aacute; de la c&uacute;pula del trueno',1985, 28);
INSERT INTO pelicula (peliculaId, nombre, anio, generoId) VALUES (240832,'Lucy',2014, 28);
INSERT INTO pelicula (peliculaId, nombre, anio, generoId) VALUES (8810,'Mad Max II, el guerrero de la carretera',1981, 28);
INSERT INTO pelicula (peliculaId, nombre, anio, generoId) VALUES (98566,'Las Tortugas Ninja',2014, 28);